# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "CTA"
  description: "Final call to action on the page"
  icon: commit
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Want to learn more about Datadog?"
  subtitle: "Datadog hosts events both online and in-person. See all that Datadog has to offer visiting our Events &amp; Webinars hub."
  link:
    url: "https://www.datadoghq.com/events-webinars/"
    text: "learn more"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  subtitle:
    type: textarea

