# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Features"
  description: "List of product features with associated video"
  icon: star
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  comment: "For the proof of concept, this component is not editable but could be in a production version." 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  comment:
    type: textarea
