# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
    - below_blocks
  label: "Heading"
  description: "A main title on the page"
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  element: "h1"
  text: "I'm a heading"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  element:
    type: select
    options:
      values:
        - h1
        - h2
        - h3
        - h4
