# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Blog container"
  description: "Shows the latest blog post"
  icon: rss_feed
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image: 
  subtitle:
  title:
  body:
  button_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  body:
    type: textarea